// <auto-generated />
using GameDownloader.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDownloader.Migrations
{
    [DbContext(typeof(GameDownloaderContext))]
    [Migration("20230404155236_InitialMigrationCreateDB")]
    partial class InitialMigrationCreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GameDownloader.Domain.Game", b =>
                {
                    b.Property<int>("idGame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("GameFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idGame");

                    b.ToTable("GAME", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
